version: "3.8"

services:
  tszalama_urlshortener_mongo_db:
    image: mongo:latest
    container_name: "tszalama_urlshortener_mongo_db"
    ports:
      - 27017:27017
    networks:
      - tszalama_urlshortener_network
    volumes:
      - tszalama_urlshortener_data:/data/db

  tszalama_shorturlapi:
    image: tszalama/shorturlapi:v1.0
    ports:
      - 9090:8080
    networks:
      - tszalama_urlshortener_network
    depends_on:
      - tszalama_urlshortener_mongo_db

networks:
  tszalama_urlshortener_network:
    driver: bridge

volumes:
  tszalama_urlshortener_data: